#!/bin/bash

#---------------------------------------------------------
# Assignment Submission Tool
#
# Name: submitzip
#
# Written by: Matthew Rowlandson - January 2017
#
# Purpose: Zips up the specified lab directory for submission
#
# Usage: ./submitzip <labname>
#       eg ./submitzip lab1
#----------------------------------------------------------

zip -r $HOME/$LOGNAME_$1.zip $HOME/$1